### ISSUE TITLE
Websocket/UART command to make ESP forget current wifi settings

### ISSUE THREAD

**Issue by ghost** [LaserWeb/LaserWeb3-ESP8266#1]
@DarklyLabs requested

**Comment by cprezzi** [comment]
@DarklyLabs I guess you mean via serial? Via websocket probably wouldn't make sense when your network is not connected ;)

**Comment by cprezzi** [comment]
Or probably it would be the easyest to do it via a input pin, so you could just pull the pin low to reset?

**Comment by ghost** [comment]
Input pin is the way to go,  but unfortunately no pins broken out on
Darkly's PCB.  Next revision will have a reset config button

**Comment by ghost** [comment]
And websocket may still be a case,  if you want to swop from one AP to
another,  network would be up

On Feb 5, 2017 1:50 PM, "Claudio Prezzi" <notifications@github.com> wrote:

I guess you mean via serial? Via websocket probably wouldn't make sense
when your network is not connected ;)

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/LaserWeb/LaserWeb3-ESP8266/issues/1#issuecomment-277514791>,
or mute the thread

**Comment by cprezzi** [comment]
Done :)
You can now pull GPIO0 to ground to reset WiFi settings and reboot.
If you are using a nodeMCU, you can just push the flash button.

**Comment by cprezzi** [comment]
If WiFi is still working, we could probably add a resetSettings function to the web page on the ESP.
But that would need some sort of password protection.

**Comment by cprezzi** [comment]
It's not so easy to do it via the webpage, but I have added it to the websocket.
You can send "resetWiFi" (upper-/lowercase) from LW3 console to clean WiFi settings (as long as it is connected).

**Comment by cprezzi** [comment]
I had problems when testing: The WiFi credentials always was deleted short time after the socket has connected. I didn't find the problem yet, so I had to remove both reset variants until I have found a solution. Sorry!

**Comment by ghost** [comment]
No problem (:

@DarklyLabs no chance we can tack a panel mount button onto the GPIO pin of
the esp?  (ps maybe dont use gpio0,  rather say gpio4 or 5, and only check
it in setup() -  that way it can function as a 'hold down during power up
to clear wifi'

**Comment by cprezzi** [comment]
Yes, that would be an option. 
I tried to only check the pin aslong as the socket has not connected, but still got the same problem.

**Comment by ghost** [comment]
This really is more of a hardware problem.  The WifiManager library boots
into Config mode if the station cannot connect to the configured AP.  So if
you replace AP,  move to new office,  lend it to a friend,  those are
covered.  I am actually unsure why you want to enter config mode
otherwise...

**Comment by ghost** [comment]
https://github.com/tzapu/WiFiManager#how-it-works explains it nicely

**Comment by cprezzi** [comment]
The thing is, as long as I only config the ESP and reboot it, the settings are held and the ESP reconnects to the configured WLAN. But if I connect via websocket and reboot, the settings seems to be lost and the ESP is booting into AP-Mode.

**Comment by cprezzi** [comment]
I will test some more the next days, but first I need to progress on the LW4 comms integration ;)

**Comment by ghost** [comment]
Agreed,  99% of our users are usb (:
