### ISSUE TITLE
Integrate Update Server 

### ISSUE THREAD

**Issue by ghost** [LaserWeb/LaserWeb3-ESP8266#2]
I have spent the whole day evaluating OTA (espota.py) (way too often fails during upload, then needs serial connection to recover)  vs central update server (too risky) and the third option, straight from the example https://github.com/esp8266/Arduino/blob/09826c6d87e54c15422da90f060377c9ef188947/libraries/ESP8266HTTPUpdateServer/examples/SecureWebUpdater/SecureWebUpdater.ino

Presents the user with a webpage where they can upload a new ESP8266 firmware bin.

This is closest to regular end-user experience for updating firmware for things like routers, etc

**Comment by ghost** [comment]
![update](https://cloud.githubusercontent.com/assets/7695323/23458359/a8b90442-fe84-11e6-85cb-c44b408df83a.PNG)


@DarklyLabs  - for updating firmware on the ESP in the future

**Comment by ghost** [comment]
Committed:

https://github.com/LaserWeb/LaserWeb3-ESP8266/commits/master

@DarklyLabs please test and use the updated image with all the next shipments. Will work better out in the field than the OTA version

@cprezzi I had to introduce a breaking change in the name of consumer experience.  This needs WebSocketServer and WebServer running.  So I changed WebSocketServer to port :81 - thus letting WebServer run on :80
Figure its easier for us to code in a port check than to force users to type ports

**Comment by cprezzi** [comment]
@openhardwarecoza I think this is not a problem. I could use port 81 by default for ESP connections and additionally allow to enter the port togheter with the IP, if needed.

**Comment by ghost** [comment]
Thanks! Sorry, otherwise i'd have to rewrite Links2004s websocketserver
library to also handle that (:

**Comment by ghost** [comment]
@openhardwarecoza @cprezzi 
Tested the updated image today and there is a problem. The new software will allow the network configuration window to appear, but will not allow LW to connect to the machine.

 Connecting Machine @ ESP8266,192.168.15.24
 Server error: unexpected server response (404)

I went back and tested the previous iteration (original wifinamager.h & Arduino project) and it worked as expected.

**Comment by cprezzi** [comment]
@DarklyLabs This is probably because lw.comm-server still tries to connect to websocket on port 80. I didn't change that yet.
If I would just change it non configurable, then all ESPs with older firmwares would not work anymore. 
So I have to make it configurable, which takes some time.

**Comment by ghost** [comment]
@cprezzi We have direct access to all machines sent out with the old firmware and it will not be a problem for us to update it.
I would rather have this done once and then we start using this one version instead of having to manage two versions out in the field.
If you could just change it non-configurable it will work for us and get us out of this problem more quickly.
Thank you.

**Comment by cprezzi** [comment]
@openhardwarecoza Do you think there are other people allready using LW with ESP connection, other than Darklys users? Or is it save to just change the port?

**Comment by ghost** [comment]
No one that i know of. I'd say break it (: we will then hear who does

**Comment by ghost** [comment]
@cprezzi Please let me know when you have changed the port. We are keen to test and release Peter's updated version onto our machines.

@openhardwarecoza The update page appears to be popping up. We haven't tried updating the firmware yet. Did you test that during your dev?

**Comment by ghost** [comment]
Yes i did.

In arduino, compile with verbose log. It shows where the bin/hex is saved.
Upload it and test again.

It will only fail if the incorrect memory size is configured when it was
originally uploaded over serial, or if the compiled hex you upload is for
the wrong flash size. (tools, flash size. I use the esp12e so its 4mb (1mb
spiffs)

**Comment by cprezzi** [comment]
@DarklyLabs I have checked my source code and you should already be able to include the port in the machine ip field (ie: 192.168.4.1:**81**). Could you test that please?

**Comment by ghost** [comment]
@openhardwarecoza Hmm.. Ok, just tried writing the compiled bin back onto itself without success. I'll have to look further into the arduino settings we are using to flash it in the first place.

**Comment by ghost** [comment]
Under the esp8266 examples is a test sketch (file, examples. Esp8266,
CheckFlashConfig). Upload it and check the serial monitor

**Comment by ghost** [comment]
@cprezzi Port 81 in ip field works. We can connect via WIFI. Thank you.

**Comment by ghost** [comment]
@openhardwarecoza Retried with 4mb (1mb spiffs) and the update was successful.
Re-wrote your latest version back onto itself.
thx.

**Comment by ghost** [comment]
Good stuff. Yeah that one often catches me. If you close arduino and open
it again it sometimes jumps back to 512k(64k spiffs), which still uploads
as our sketch is small. I also have a mix of esp7s (1mb) and esp12s (4mb)
on hand, so sometimes between projects i forget to change it

**Comment by ghost** [comment]
@openhardwarecoza Yeah, it was working correctly until we tried to update.
Are you confident that this recent arduino sketch, update method etc will not change in the short term? 
If not, we will proceed to update all our machines in the field and about to go out.

**Comment by ghost** [comment]
Confidence level, 20% (:

The whole esp8266 thing really should be seen as a 'experimental' feature -
no where near enough testing has been done on it to say anything is set in
stone. At least those that now go out, we can document a process for users
to replace that with a new firmware.

But as i show in github.com/LaserWeb/projects - dont consider wifi/telnet
part of this releases plans yet. Its way too untested

**Comment by ghost** [comment]
In fact i am almost certainly switching from. Websocket to Telnet in a
couple weeks... Much faster. Look at the other open ticket here. But thats
not ready to install now.

**Comment by ghost** [comment]
@openhardwarecoza Thanks for the update. As long as we can use the existing methodology to update out in the field then this is as good a starting point as any.

**Comment by radiolee** [comment]
Another idea to update firmware via wifi:
https://github.com/sauloalrpi/WebSocketServerShortFS
Format 256kB of Flash as SPIFFS, ESP-01 1M(256k SPIFFS),  the .bin compressed at highest rate using GZIP is only 240kB, upload to the sketch and flash.
