### ISSUE TITLE
Credentials not removed even after re-flashing

### ISSUE THREAD

**Issue by ghost** [LaserWeb/LaserWeb3-ESP8266#3]
We have noticed that even after re-flashing the arduino project to the ESP module, it still retained the login credentials to our network.

Ideally we need the ability to completely wipe this information from the ESP module during the flashing process.

How can this be done?

**Comment by ghost** [comment]
I guess this is related to the original issue:
https://github.com/LaserWeb/LaserWeb3-ESP8266/issues/1

**Comment by ghost** [comment]
https://github.com/LaserWeb/LaserWeb3-ESP8266/blob/master/websocketserver.ino/websocketserver.ino.ino#L143

(wiring up a gpio button to call that function, instead of in setup() would
be the ideal solution)

**Comment by ghost** [comment]
we do have buttons on our PCB to allow for programming. We have ESP flash and ESP boot which we press in the correct sequence to initiate programming.
These are not accessible by the user unfortunately unless they open the machine up.

But, if we can use them to clear the credentials it will be a big help.

Is this possible now or will it require some programming work?

**Comment by ghost** [comment]
Needs adding to the sketch. Which GPIO ie tied to the program button?
GPIO0?

**Comment by cprezzi** [comment]
@openhardwarecoza Did you see that I had that programmed already, but had to comment out the reset, because I lost the credentials on every boot?
It was working with flash button (GPIO0) or by sending resetWiFi to websocket.

**Comment by cprezzi** [comment]
Since you have integrated the WebUpdate server, could you add a second url like "/resetWiFi" with username and password?

**Comment by cprezzi** [comment]
@DarklyLabs Do you use a NodeMCU board or something you have developped?

**Comment by ghost** [comment]
Darkly has a custom pcb running smoothieware, with an esp onboard.

I didnt see it, sorry Claudio, havent dug in at all in a long time. Just
added the update server.

Adding a web based reset is one option, by nature WifiManager handles most
cases anyway (ie if network not available, fall back to be an AP)

In fact, not sure why Darkly would want to reset wifi at all? Test at the
office. Ship to customer. Customer powers on, but since Darkly office wifi
isnt available, fails to connect. That kicks it into AP mode. Customer
connects to AP and opens browser. Browser is sandboxed in captive portal
showing Wifi config. User picks own wifi network. Done

**Comment by cprezzi** [comment]
Whith the fallback to AP-Mode when not possible to connect to configured network, there is no need for a manual reset at all.

**Comment by ghost** [comment]
my thinking too, which is why, at the very beginning, i went with WifiManager. Maybe a case of "didnt test, didnt read?" - https://github.com/tzapu/WiFiManager

**Comment by cprezzi** [comment]
I'm guilty too! Didn't read that ;)

**Comment by ghost** [comment]
In the big scheme of things this is not a critical issue. This issue was labeled as a question as to why reflashing the ESP firmware didn't clear previous credentials.

We will implement a check for button press to issue the reset command in the Arduino 'setup' section. This will allow is to do all our testing etc.

Thanks for the feedback and info. I will close this off now because I'm sure you have much more pressing work that needs attention.

All help and feedback has been very much appreciated.
