### ISSUE TITLE
single or double quotes in string indexOf

### ISSUE THREAD

**Issue by arkypita** [LaserWeb/LaserWeb3-ESP8266#4]
`if (command.indexOf('resetWiFi') != -1)`

I am not sure, but I think that the use of a double quote instead of single quote should be more correct

**Comment by tbfleming** [comment]
It's not.

**Comment by tbfleming** [comment]
Whoops. Didn't realize this is on one of our C++ repos.

**Comment by tbfleming** [comment]
Yes. You are correct.

**Comment by arkypita** [comment]
I am not a c++ master, but I think single quote will be interpreted as char[] and indexOf fail looking only for the first character of the string.

Anyway the best way to test a string against a string is by ==
`if (command == "resetWiFi\n")`

however not a big issue

**Comment by cprezzi** [comment]
Ups, that was my fault. That's probably the reason why this feature was never working ;)
(too much php programming)

Corrected with commit https://github.com/LaserWeb/LaserWeb3-ESP8266/commit/6aecd95750784ea37a05579230c0ca71e2933c80

**Comment by ghost** [comment]
@cprezzi Can you explain what problems this would have caused?
Could it be related to the poor performance over wifi?

**Comment by cprezzi** [comment]
@domenic-d The error could have caused to go though that if block each time an `r` was detected in the stream, which would lead to the execution of unnecessary delay commands (500+100ms), but I don't think we have any `r` in the Gcode.

Could you test if it makes a difference?

**Comment by ghost** [comment]
@cprezzi Will compile and test today. thanks.

**Comment by arkypita** [comment]
Sincerly I don't think that the sketch has any particular problems. I am using "as is" (with or without the part that check for "resetWiFi") with my LaserGRBL program and it works good.

![with lasergrbl](https://user-images.githubusercontent.com/8782035/27773845-5f24eec6-5f83-11e7-8f2b-ec06b12b5692.jpg)

With LaserWeb4 I have this problems:
![image](https://user-images.githubusercontent.com/8782035/27773847-6ba6c2fa-5f83-11e7-9d76-94303dc67405.png)
![image](https://user-images.githubusercontent.com/8782035/27773848-70c833a4-5f83-11e7-930e-99fa09a2fe1b.png)

and the sequence in command log show

```
 Connecting Machine @ ESP8266,192.168.1.170:81
 Machine connected
 Connected
 No supported firmware detected. Closing connection to 192.168.1.170:81
```

**Comment by cprezzi** [comment]
@arkypita Sorry, my mistake. Corrected with commit https://github.com/LaserWeb/lw.comm-server/commit/41f0844fe40e69f20c6373ab904c0e006e2362dc

**Comment by arkypita** [comment]
I have tested, it work.

![laserweb](https://user-images.githubusercontent.com/8782035/27819898-9263817a-609c-11e7-9714-b15c39786cab.jpg)

Anyway it remains a little problem. When LaserWeb connects to ESP it expects to receive the version string. If it does not receive, it declares "not supported firmware detected".

To be able to successfully connect I had to manual reset my arduino (pressing reset button) during the  firmware version check phase. I think LaserWeb must send a ^X reset command to grbl to be sure to recevive the [welcome message](https://github.com/gnea/grbl/wiki/Grbl-v1.1-Interface#welcome-message)

Or alternatively it can be done in ESP sketch at client connection.

```
case WStype_CONNECTED: {
            IPAddress ip = webSocket.remoteIP(num);
            socketConnected = true;
            webSocket.sendTXT(num, "Connected");
            //TODO: send ^X command to arduino
        }
```

**Comment by cprezzi** [comment]
There is a environment variable for that. Just create a file called `.env` (nothing in front of the point!) in the installation folder with a line `RESET_ON_CONNECT=1`

**Comment by cprezzi** [comment]
Inserting this in the ESP code is also a good idea! Thanks.

**Comment by arkypita** [comment]
sounds good, issue closed
