### ISSUE TITLE
Is this for laserweb4?

### ISSUE THREAD

**Issue by radiolee** [LaserWeb/LaserWeb3-ESP8266#6]
readme say this is for LaserWeb3, can I use this firmware for lw4 connection?

**Comment by cprezzi** [comment]
You can try it, but LW4 doesn't officially support connection via ESP8266, because it's too slow and never was stable enough.

**Comment by radiolee** [comment]
@cprezzi thanks for reply.

**Comment by radiolee** [comment]
My ESP01 board arrived and got working as softap now with no issues. Next I'll try connection to LW4.
Is resetWifi back now?
